spring:
    application:
        name: UserCRUD
    datasource:
        username: springuser
        password: admin
        url: "jdbc:mysql://localhost:3306/user_database"

server:
    port: 8080
    servlet:
        context-path: /identity

jwt:
    signerKey: "kO8X8RAuhKAe3ydhZdpEQbNt6rQvPmFmwUtX0Z/TkAescDY4NADgG1EIqMvAP7g7"
    valid-duration: 3600
    refreshable-duration: 36000

